(dribble "mp1.out")
(load "main.lisp")
(print (format nil "~%Test blockpuzzle for various puzzles (not from input file).~%"))
(blockpuzzle '())
(blockpuzzle '(O))
(blockpuzzle '(O W))
(blockpuzzle '(O B W))
(blockpuzzle '(B W W O))
(blockpuzzle '(B B W O B W))
(blockpuzzle '(B W W B O B W W B))
(print (format nil "~%Verify blockpuzzle works for a properly formatted input file~%"))
(blockpuzzle nil :input-file "mp1.in_test1")
(print (format nil "~%Note: Bigger puzzles will take too long to compute.~%"))
(dribble)